import Link from "next/link";
import { Logo } from "@/components/Logo";
const leads=[
  {name:"Chinedu Okafor",source:"Telegram",interest:"Copy Trading",stage:"Qualified",value:"₦3.5m"},
  {name:"Amara Williams",source:"Email",interest:"Expert Advisor",stage:"Follow-up",value:"₦920k"},
  {name:"Tunde Balogun",source:"Outbound Call",interest:"Indicator Suite",stage:"Demo booked",value:"₦480k"},
  {name:"Sarah Mensah",source:"Website",interest:"Core Profile",stage:"New",value:"₦2.1m"},
];
export default function Dashboard(){return <main className="dashboardPage"><aside className="dashSide"><Logo/><nav><span className="active">Overview</span><span>Leads</span><span>Campaigns</span><span>Calls</span><span>Emails</span><span>Telegram</span><span>Products</span><span>Settings</span></nav><Link href="/">← Website</Link></aside><section className="dashMain"><header><div><span className="kicker">SALES OPERATIONS</span><h1>Gencouv Command Center</h1></div><button>+ New campaign</button></header><div className="dashMetrics"><article><span>Total pipeline</span><strong>₦7.0m</strong><small>+18.4% this month</small></article><article><span>Qualified leads</span><strong>284</strong><small>47 added this week</small></article><article><span>Telegram starts</span><strong>126</strong><small>44.3% conversion</small></article><article><span>Meetings booked</span><strong>38</strong><small>13.4% of leads</small></article></div><div className="dashLayout"><article className="dashPanel wide"><div className="dashPanelHead"><h2>Revenue pipeline</h2><span>Last 30 days</span></div><div className="bars">{[42,64,48,78,58,88,72,96,82,110,94,128].map((h,i)=><i key={i} style={{height:`${h}px`}}></i>)}</div><div className="axis"><span>Week 1</span><span>Week 2</span><span>Week 3</span><span>Week 4</span></div></article><article className="dashPanel"><div className="dashPanelHead"><h2>Agent status</h2><span className="greenText">All systems online</span></div><div className="agentList"><div><i></i><span>Lead generation</span><b>Apify</b></div><div><i></i><span>Email sequence</span><b>Workspace</b></div><div><i></i><span>Call outbound</span><b>Retell</b></div><div><i></i><span>Telegram onboarding</span><b>Active</b></div></div></article><article className="dashPanel full"><div className="dashPanelHead"><h2>Recent leads</h2><button>View all</button></div><div className="leadTable"><div className="tr head"><span>Lead</span><span>Source</span><span>Interest</span><span>Stage</span><span>Potential</span></div>{leads.map(l=><div className="tr" key={l.name}><span><b>{l.name}</b><small>Contact record</small></span><span>{l.source}</span><span>{l.interest}</span><span><em>{l.stage}</em></span><span>{l.value}</span></div>)}</div></article></div></section></main>}
